stages:
  - test

variables:
  # Default values that can be overridden by GitLab CI/CD variables
  DB_NAME_DEFAULT: "oracle_db_name"
  DB_USER_DEFAULT: "db_username"
  DB_PASSWORD_DEFAULT: "db_password"
  DB_HOST_DEFAULT: "db_host"
  # Test configuration defaults
  VALIDATE_FIELDS_DEFAULT: "TRUE"

# Job to run the CHARGEMENT tests
chargement_tests:
  stage: test
  image: python:3.9
  before_script:
    # Install Robot Framework and required libraries
    - pip install robotframework
    - pip install robotframework-databaselibrary
    - pip install oracledb

    # Create directories needed for tests
    - mkdir -p input archive rej

    # Create a variables file with the database credentials and test configuration from GitLab CI/CD variables
    - |
      cat > Resources/variables_ci.robot << EOF
      *** Variables ***
      # Database connection variables from GitLab CI/CD
      \${DB_NAME_VAR}         ${DB_NAME:-$DB_NAME_DEFAULT}
      \${DB_USER_VAR}         ${DB_USER:-$DB_USER_DEFAULT}
      \${DB_PASSWORD_VAR}     ${DB_PASSWORD:-$DB_PASSWORD_DEFAULT}
      \${DB_HOST_VAR}         ${DB_HOST:-$DB_HOST_DEFAULT}

      # Test configuration variables from GitLab CI/CD
      \${VALIDATE_FIELDS}     ${VALIDATE_FIELDS:-$VALIDATE_FIELDS_DEFAULT}
      EOF

    # Import the CI variables into the main variables file
    - |
      cat >> Resources/variables.robot << EOF

      # Import CI variables
      Resource    variables_ci.robot
      EOF
  script:
    # Run the CHARGEMENT tests
    - robot -d Results Tests/CHARGEMENT/chargement_tests.robot
  artifacts:
    paths:
      - Results/
    expire_in: 1 week
